# Generated by Django 4.1.3 on 2023-11-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score', models.IntegerField()),
                ('table_id', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('query_id', models.CharField(max_length=255)),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.score')),
            ],
        ),
    ]
